extends:
  - prettier
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  no-console: 0
  import/no-unresolved: 0
  import/extensions:
    - .js
    - .json
globals:
  test: true
  expect: true
  afterAll: true
